// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJLE70cGUNwT0ZiIrMZu5Cm30HHzIhscA',
    appId: '1:701893217590:web:28c7eaf768ab0250c07797',
    messagingSenderId: '701893217590',
    projectId: 'fixmate-7a0e1',
    authDomain: 'fixmate-7a0e1.firebaseapp.com',
    storageBucket: 'fixmate-7a0e1.firebasestorage.app',
    measurementId: 'G-CJC3CE6WC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjQxK0voFw7ui55OIszD2eCimLilt_mWA',
    appId: '1:701893217590:android:7b04baa099850dd1c07797',
    messagingSenderId: '701893217590',
    projectId: 'fixmate-7a0e1',
    storageBucket: 'fixmate-7a0e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1gESdp5Pq3ymJ5VcX0tIJasBdYYfIDdo',
    appId: '1:701893217590:ios:b2f30a9d8bbfc909c07797',
    messagingSenderId: '701893217590',
    projectId: 'fixmate-7a0e1',
    storageBucket: 'fixmate-7a0e1.firebasestorage.app',
    iosBundleId: 'com.example.fixmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1gESdp5Pq3ymJ5VcX0tIJasBdYYfIDdo',
    appId: '1:701893217590:ios:b2f30a9d8bbfc909c07797',
    messagingSenderId: '701893217590',
    projectId: 'fixmate-7a0e1',
    storageBucket: 'fixmate-7a0e1.firebasestorage.app',
    iosBundleId: 'com.example.fixmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJLE70cGUNwT0ZiIrMZu5Cm30HHzIhscA',
    appId: '1:701893217590:web:621f00a362978f19c07797',
    messagingSenderId: '701893217590',
    projectId: 'fixmate-7a0e1',
    authDomain: 'fixmate-7a0e1.firebaseapp.com',
    storageBucket: 'fixmate-7a0e1.firebasestorage.app',
    measurementId: 'G-0FPPFJ9C3W',
  );
}
